version: '3.8'
services:
  gcopy:
    container_name: gcopy
    build: ../build/gcopy
    restart: always
    # ports: 通过 NPM proxy
    #   - "3376:3376"
    command: ["--app-key=<app-key>", "--smtp-host=<smtp-host>", "--smtp-port=<smtp-port>", "--smtp-username=<smtp-username>", "--smtp-password=<smtp-password>", "--smtp-ssl"]

  gcopy-frontend:
    container_name: gcopy-frontend
    build: ../build/frontend
    restart: always
    # ports: 通过 NPM proxy
    #   - "3375:3375"
    volumes:
      - ./frontend/.env.production:/app/.env.production
    depends_on:
      - gcopy
